# .github/workflows/rails_ci.yml

name: Rails CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      POSTGRES_USER: mypostgresuser  # Set the PostgreSQL superuser username
      POSTGRES_PASSWORD: mysecretpassword  # Set the PostgreSQL superuser password
      POSTGRES_DB: test_app_development  # Set the development database name

    services:
      db:
        image: postgres:14.9
        ports:
          - '5432:5432'
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5.8  # Change to your desired Ruby version

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14  # Change to your desired Node.js version
      
      - name: Start PostgreSQL Service
        run: sudo service postgresql start 
      
      - name: Build and run test
        env: 
          DATABASE_URL: postgres://mypostgresuser:mysecretpassword@localhost:5432/test_app_development
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: |
          gem install bundler -v 2.3.26
          bundle install
          yarn install

      - name: Run tests
        run: |
          bundle exec rails db:create
          bundle exec rails db:migrate
          bundle exec rspec
